/* ============================================================
   HomeDuty (Family Task & Planning) — PostgreSQL Schema
   Meets lab requirements:
   - >= 4 tables, each >= 10 rows (seeded below)
   - PK/FK with ON DELETE rules (delete constraint)
   - Number constraints (CHECK)
   - View (CREATE VIEW) for UI
   - Index for UI search
   - Sequence used for auto-assign
   - UNION + EXCEPT examples (UNION in a view, EXCEPT in a function)
   - Aggregate + HAVING (inside cursor function via min_points)
   - 3 SQL functions (one uses RECORD + CURSOR)
   - 2 triggers (award points + auto badge)
   - 2 roles (admin/user) + grants (best-effort; may skip if no privilege)
   ============================================================ */

-- ---------- RESET ----------
DROP SCHEMA IF EXISTS homeduty CASCADE;
CREATE SCHEMA homeduty;
SET search_path = homeduty;

-- ---------- SEQUENCE (required) ----------
CREATE SEQUENCE seq_family_id START 1001 INCREMENT 1;
CREATE SEQUENCE seq_task_id   START 2001 INCREMENT 1;

-- ---------- TABLES (4 tables) ----------
/* Families */
CREATE TABLE family (
  family_id  INT PRIMARY KEY DEFAULT nextval('seq_family_id'),
  name       TEXT NOT NULL UNIQUE
);

/* Users (role requirement can be app-level, but we also store a role column) */
CREATE TABLE app_user (
  user_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id    INT NOT NULL REFERENCES family(family_id) ON DELETE CASCADE,
  full_name    TEXT NOT NULL,
  email        TEXT NOT NULL UNIQUE,
  role         TEXT NOT NULL CHECK (role IN ('admin','member')),
  points_total INT NOT NULL DEFAULT 0 CHECK (points_total >= 0),
  badge        TEXT NOT NULL DEFAULT 'None'
);

/* Tasks (number constraint via difficulty) */
CREATE TABLE task (
  task_id     INT PRIMARY KEY DEFAULT nextval('seq_task_id'),
  family_id   INT NOT NULL REFERENCES family(family_id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  frequency   TEXT NOT NULL CHECK (frequency IN ('daily','weekly')),
  difficulty  INT  NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (family_id, title)
);

/* Assignments (delete constraints via ON DELETE rules) */
CREATE TABLE assignment (
  assignment_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id           INT NOT NULL REFERENCES task(task_id) ON DELETE CASCADE,
  assigned_to       INT NOT NULL REFERENCES app_user(user_id) ON DELETE RESTRICT, -- delete constraint example
  week_start        DATE NOT NULL,
  status            TEXT NOT NULL DEFAULT 'assigned'
                   CHECK (status IN ('assigned','done','missed')),
  points_awarded    INT NOT NULL DEFAULT 0 CHECK (points_awarded >= 0),
  last_trigger_msg  TEXT
);

-- ---------- INDEX (required) ----------
-- UI search typically: "show my assignments for a specific week"
CREATE INDEX idx_assignment_week_user ON assignment (week_start, assigned_to);

-- Optional helpful search index (task title search)
CREATE INDEX idx_task_title ON task (title);

-- ---------- VIEWS (at least one view must be called from UI) ----------
/* Scoreboard view (UI can filter by family_id and week_start) */
CREATE OR REPLACE VIEW vw_weekly_scoreboard AS
SELECT
  u.family_id,
  a.week_start,
  u.user_id,
  u.full_name,
  SUM(a.points_awarded) AS total_points,
  COUNT(*) FILTER (WHERE a.status = 'done')   AS done_count,
  COUNT(*) FILTER (WHERE a.status = 'missed') AS missed_count,
  COUNT(*) FILTER (WHERE a.status = 'assigned') AS assigned_count
FROM app_user u
JOIN assignment a ON a.assigned_to = u.user_id
GROUP BY u.family_id, a.week_start, u.user_id, u.full_name;

/* UNION example view (activity feed; UI filters by week_start & family_id) */
CREATE OR REPLACE VIEW vw_week_activity_feed AS
SELECT
  u.family_id,
  a.week_start,
  a.assignment_id,
  u.user_id,
  u.full_name,
  t.title AS task_title,
  'DONE'::TEXT AS event_type,
  a.points_awarded AS points
FROM assignment a
JOIN app_user u ON u.user_id = a.assigned_to
JOIN task t ON t.task_id = a.task_id
WHERE a.status = 'done'

UNION ALL

SELECT
  u.family_id,
  a.week_start,
  a.assignment_id,
  u.user_id,
  u.full_name,
  t.title AS task_title,
  'MISSED'::TEXT AS event_type,
  0 AS points
FROM assignment a
JOIN app_user u ON u.user_id = a.assigned_to
JOIN task t ON t.task_id = a.task_id
WHERE a.status = 'missed';

-- ---------- FUNCTIONS (3 required) ----------
/* ------------------------------------------------------------
   1) assign_tasks_random(family_id, week_start)
   - inserts assignments for all active tasks of that family
   - assigns randomly to a member of the same family
   - returns inserted rows (for UI to list)
   ------------------------------------------------------------ */
CREATE OR REPLACE FUNCTION homeduty.assign_tasks_random(
  p_family_id INT,
  p_week_start DATE
)
RETURNS TABLE (
  assignment_id INT,
  task_id INT,
  assigned_to INT,
  week_start DATE,
  status TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
  v_user_count INT;
BEGIN
  SELECT COUNT(*) INTO v_user_count
  FROM homeduty.app_user u
  WHERE u.family_id = p_family_id;

  IF v_user_count = 0 THEN
    RAISE EXCEPTION 'No users found for family_id=%', p_family_id;
  END IF;

  INSERT INTO homeduty.assignment (task_id, assigned_to, week_start, status)
  SELECT
    t.task_id,
    u.user_id,
    p_week_start,
    'assigned'
  FROM (
    SELECT
      tk.task_id AS task_id,
      ROW_NUMBER() OVER (ORDER BY random()) AS rn
    FROM homeduty.task tk
    WHERE tk.family_id = p_family_id
      AND tk.is_active = TRUE
  ) AS t
  JOIN (
    SELECT
      au.user_id AS user_id,
      ROW_NUMBER() OVER (
        ORDER BY COALESCE(w.cnt, 0) ASC, random()
      ) AS rn
    FROM homeduty.app_user au
    LEFT JOIN (
      SELECT
        a.assigned_to AS assigned_to,
        COUNT(*) AS cnt
      FROM homeduty.assignment a
      WHERE a.week_start = p_week_start
      GROUP BY a.assigned_to
    ) AS w
      ON w.assigned_to = au.user_id
    WHERE au.family_id = p_family_id
  ) AS u
    ON ((t.rn - 1) % v_user_count) + 1 = u.rn
  WHERE NOT EXISTS (
    SELECT 1
    FROM homeduty.assignment a2
    WHERE a2.task_id = t.task_id
      AND a2.week_start = p_week_start
  );

  RETURN QUERY
  SELECT
    a3.assignment_id,
    a3.task_id,
    a3.assigned_to,
    a3.week_start,
    a3.status
  FROM homeduty.assignment a3
  JOIN homeduty.task t2 ON t2.task_id = a3.task_id
  WHERE t2.family_id = p_family_id
    AND a3.week_start = p_week_start
  ORDER BY a3.assignment_id;
END;
$$;



/* ------------------------------------------------------------
   2) get_user_pending_tasks(user_id, week_start)
   - EXCEPT requirement (called from UI)
   - returns tasks assigned this week EXCEPT tasks done this week
   ------------------------------------------------------------ */
CREATE OR REPLACE FUNCTION get_user_pending_tasks(p_user_id INT, p_week_start DATE)
RETURNS TABLE (
  task_id INT,
  task_title TEXT,
  difficulty INT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  (
    SELECT t.task_id, t.title, t.difficulty
    FROM assignment a
    JOIN task t ON t.task_id = a.task_id
    WHERE a.assigned_to = p_user_id
      AND a.week_start = p_week_start
  )
  EXCEPT
  (
    SELECT t.task_id, t.title, t.difficulty
    FROM assignment a
    JOIN task t ON t.task_id = a.task_id
    WHERE a.assigned_to = p_user_id
      AND a.week_start = p_week_start
      AND a.status = 'done'
  )
  ORDER BY task_id;
END;
$$;

/* ------------------------------------------------------------
   3) get_family_scoreboard_cursor(family_id, week_start, min_points DEFAULT 0)
   - Uses CURSOR + RECORD (required)
   - Includes aggregate + HAVING (required) via min_points
   - Returns a table for UI
   ------------------------------------------------------------ */
CREATE OR REPLACE FUNCTION get_family_scoreboard_cursor(
  p_family_id INT,
  p_week_start DATE,
  p_min_points INT DEFAULT 0
)
RETURNS TABLE (
  user_id INT,
  full_name TEXT,
  total_points INT,
  done_count INT,
  missed_count INT
)
LANGUAGE plpgsql
AS $$
DECLARE
  cur CURSOR FOR
    SELECT
      u.user_id,
      u.full_name,
      COALESCE(SUM(a.points_awarded),0) AS total_points,
      COUNT(*) FILTER (WHERE a.status='done') AS done_count,
      COUNT(*) FILTER (WHERE a.status='missed') AS missed_count
    FROM app_user u
    LEFT JOIN assignment a
      ON a.assigned_to = u.user_id
     AND a.week_start = p_week_start
    WHERE u.family_id = p_family_id
    GROUP BY u.user_id, u.full_name
    HAVING COALESCE(SUM(a.points_awarded),0) >= p_min_points
    ORDER BY total_points DESC, done_count DESC, u.full_name;

  rec RECORD;
BEGIN
  OPEN cur;
  LOOP
    FETCH cur INTO rec;
    EXIT WHEN NOT FOUND;

    user_id := rec.user_id;
    full_name := rec.full_name;
    total_points := rec.total_points;
    done_count := rec.done_count;
    missed_count := rec.missed_count;

    RETURN NEXT;
  END LOOP;
  CLOSE cur;
END;
$$;

-- ---------- TRIGGERS (2 required) ----------
/* Trigger 1: when status becomes DONE, award points and store UI message */
CREATE OR REPLACE FUNCTION trg_award_points_on_done()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_points INT;
BEGIN
  -- Fire only when status changes to 'done'
  IF TG_OP = 'UPDATE'
     AND NEW.status = 'done'
     AND OLD.status IS DISTINCT FROM NEW.status
  THEN
    SELECT difficulty * 10 INTO v_points
    FROM task
    WHERE task_id = NEW.task_id;

    NEW.points_awarded := COALESCE(v_points, 0);
    NEW.last_trigger_msg := '✅ Points awarded by trigger: +' || NEW.points_awarded;

    UPDATE app_user
    SET points_total = points_total + NEW.points_awarded
    WHERE user_id = NEW.assigned_to;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_award_points_on_done ON assignment;
CREATE TRIGGER tr_award_points_on_done
BEFORE UPDATE OF status ON assignment
FOR EACH ROW
EXECUTE FUNCTION trg_award_points_on_done();

/* Trigger 2: auto-assign badge based on points_total */
CREATE OR REPLACE FUNCTION trg_auto_badge()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.points_total >= 200 THEN
    NEW.badge := 'Gold Helper';
  ELSIF NEW.points_total >= 100 THEN
    NEW.badge := 'Silver Helper';
  ELSIF NEW.points_total >= 50 THEN
    NEW.badge := 'Bronze Helper';
  ELSE
    NEW.badge := 'None';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_auto_badge ON app_user;
CREATE TRIGGER tr_auto_badge
BEFORE UPDATE OF points_total ON app_user
FOR EACH ROW
EXECUTE FUNCTION trg_auto_badge();

-- ---------- ROLES & GRANTS (2 roles requirement; best-effort) ----------
-- Note: Creating roles needs superuser/admin rights. If you don't have it, this block will just print a NOTICE.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'homeduty_admin') THEN
    EXECUTE $sql$CREATE ROLE homeduty_admin LOGIN PASSWORD 'homeduty_admin_pw'$sql$;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'homeduty_user') THEN
    EXECUTE $sql$CREATE ROLE homeduty_user LOGIN PASSWORD 'homeduty_user_pw'$sql$;
  END IF;

  EXECUTE $sql$GRANT USAGE ON SCHEMA homeduty TO homeduty_admin, homeduty_user$sql$;

  EXECUTE $sql$GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA homeduty TO homeduty_admin$sql$;
  EXECUTE $sql$GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA homeduty TO homeduty_admin$sql$;

  EXECUTE $sql$GRANT SELECT ON ALL TABLES IN SCHEMA homeduty TO homeduty_user$sql$;
  EXECUTE $sql$GRANT UPDATE (status) ON homeduty.assignment TO homeduty_user$sql$;

EXCEPTION WHEN insufficient_privilege THEN
  RAISE NOTICE 'Skipping role creation/grants (insufficient privilege). Create roles manually if needed.';
END;
$$;


-- ---------- SEED DATA (>= 10 rows per table) ----------
-- 10 families
INSERT INTO family (name) VALUES
('Osman Family'), ('Yilmaz Family'), ('Kaya Family'), ('Demir Family'), ('Aydin Family'),
('Celik Family'), ('Sahin Family'), ('Arslan Family'), ('Koc Family'), ('Oz Family');

-- 10 users (spread across families; 2 in Osman Family for demo)
INSERT INTO app_user (family_id, full_name, email, role) VALUES
((SELECT family_id FROM family WHERE name='Osman Family'),  'Med Bou',        'med@example.com',           'admin'),
((SELECT family_id FROM family WHERE name='Osman Family'),  'Zuber Alkatma',  'zuber@example.com',         'member'),
((SELECT family_id FROM family WHERE name='Osman Family'),  'Mustafa kucuk',  'mustafa@example.com',       'admin'),
((SELECT family_id FROM family WHERE name='Osman Family'),  'Report Member',  'report.user@example.com',   'member'),
((SELECT family_id FROM family WHERE name='Osman Family'), 'Hussein Osman', 'hussein.admin@example.com',   'admin'),
((SELECT family_id FROM family WHERE name='Yilmaz Family'), 'Ayse Yilmaz',    'ayse@example.com',          'admin'),
((SELECT family_id FROM family WHERE name='Kaya Family'),   'Mehmet Kaya',    'mehmet@example.com',        'member'),
((SELECT family_id FROM family WHERE name='Demir Family'),  'Elif Demir',     'elif@example.com',          'member'),
((SELECT family_id FROM family WHERE name='Aydin Family'),  'Can Aydin',      'can@example.com',           'admin'),
((SELECT family_id FROM family WHERE name='Celik Family'),  'Zeynep Celik',   'zeynep@example.com',        'member'),
((SELECT family_id FROM family WHERE name='Sahin Family'),  'Mert Sahin',     'mert@example.com',          'member'),
((SELECT family_id FROM family WHERE name='Arslan Family'), 'Derya Arslan',   'derya@example.com',         'admin'),
((SELECT family_id FROM family WHERE name='Koc Family'),    'Ali Koc',        'ali@example.com',           'member');

-- 10 tasks (mostly for Osman Family so your demo has meaningful UI data)
INSERT INTO task (family_id, title, frequency, difficulty, is_active) VALUES
((SELECT family_id FROM family WHERE name='Osman Family'), 'Take out trash',       'daily',  2, TRUE),
((SELECT family_id FROM family WHERE name='Osman Family'), 'Grocery shopping',     'weekly', 4, TRUE),
((SELECT family_id FROM family WHERE name='Osman Family'), 'Pay electricity bill', 'weekly', 3, TRUE),
((SELECT family_id FROM family WHERE name='Osman Family'), 'Wash dishes',          'daily',  2, TRUE),
((SELECT family_id FROM family WHERE name='Osman Family'), 'Vacuum living room',   'weekly', 3, TRUE),
((SELECT family_id FROM family WHERE name='Osman Family'), 'Laundry',              'weekly', 3, TRUE),
((SELECT family_id FROM family WHERE name='Osman Family'), 'Cook dinner',          'daily',  4, TRUE),
((SELECT family_id FROM family WHERE name='Osman Family'), 'Clean bathroom',       'weekly', 5, TRUE),
((SELECT family_id FROM family WHERE name='Osman Family'), 'Water plants',         'daily',  1, TRUE),
((SELECT family_id FROM family WHERE name='Osman Family'), 'Feed pets',            'daily',  1, TRUE);


-- Demo: mark a few assignments as done to show trigger works (points_awarded + message + badge updates)
-- (In your live demo, do this from the UI instead.)
UPDATE assignment
SET status = 'done'
WHERE week_start = DATE '2026-01-05'
  AND assignment_id IN (SELECT assignment_id FROM assignment ORDER BY assignment_id LIMIT 5);

-- Quick sanity check queries (optional):
-- SELECT * FROM vw_weekly_scoreboard WHERE family_id = (SELECT family_id FROM family WHERE name='Osman Family') AND week_start = DATE '2026-01-05';
-- SELECT * FROM vw_week_activity_feed WHERE family_id = (SELECT family_id FROM family WHERE name='Osman Family') AND week_start = DATE '2026-01-05';
-- SELECT * FROM get_user_pending_tasks((SELECT user_id FROM app_user WHERE email='hussein.admin@example.com'), DATE '2026-01-05');
-- SELECT * FROM get_family_scoreboard_cursor((SELECT family_id FROM family WHERE name='Osman Family'), DATE '2026-01-05', 0);

-- tables
SELECT table_name
FROM information_schema.tables
WHERE table_schema='homeduty'
ORDER BY table_name;

-- sample: scoreboard view exists
SELECT * FROM homeduty.vw_weekly_scoreboard LIMIT 5;
select * from homeduty.app_user;
select * from homeduty.task;
select * from homeduty.assignment;
select f.name, u.full_name from homeduty.family f, homeduty.app_user u 
where f.family_id = u.family_id and f.name = 'Osman Family';



-- sample: your seeded users exist
SELECT user_id, email, role, family_id
FROM homeduty.app_user
ORDER BY user_id;